before_script:
  - npm install;
  - npm i -g firebase-tools
script:
  - gulp test 
  - gulp
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN} 
language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
